//
//  DataOfDaysOfTheWeek.swift
//  FooTeam
//
//  Created by Виталий Сосин on 16.11.2020.
//  Copyright © 2020 Vitalii Sosin. All rights reserved.
//

import Foundation

class DataOfDaysOfTheWeek {
    static let shared = DataOfDaysOfTheWeek()
    
    var days: [[String]] = [
        [NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayMonday", comment: "Monday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayTuesday", comment: "Tuesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayWednesday", comment: "Wednesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayThursday", comment: "Thursday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayFriday", comment: "Friday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySaturday", comment: "Saturday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySunday", comment: "Sunday")],
        [NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayMonday", comment: "Monday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayTuesday", comment: "Tuesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayWednesday", comment: "Wednesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayThursday", comment: "Thursday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayFriday", comment: "Friday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySaturday", comment: "Saturday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySunday", comment: "Sunday")],
        [NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayMonday", comment: "Monday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayTuesday", comment: "Tuesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayWednesday", comment: "Wednesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayThursday", comment: "Thursday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayFriday", comment: "Friday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySaturday", comment: "Saturday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySunday", comment: "Sunday")],
        [NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayMonday", comment: "Monday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayTuesday", comment: "Tuesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayWednesday", comment: "Wednesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayThursday", comment: "Thursday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayFriday", comment: "Friday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySaturday", comment: "Saturday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySunday", comment: "Sunday")],
        [NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayMonday", comment: "Monday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayTuesday", comment: "Tuesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayWednesday", comment: "Wednesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayThursday", comment: "Thursday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayFriday", comment: "Friday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySaturday", comment: "Saturday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySunday", comment: "Sunday")],
        [NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayMonday", comment: "Monday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayTuesday", comment: "Tuesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayWednesday", comment: "Wednesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayThursday", comment: "Thursday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayFriday", comment: "Friday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySaturday", comment: "Saturday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySunday", comment: "Sunday")],
        [NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayMonday", comment: "Monday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayTuesday", comment: "Tuesday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayWednesday", comment: "Wednesday"), NSLocalizedString(NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayThursday", comment: ""), comment: "Thursday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdayFriday", comment: "Friday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySaturday", comment: "Saturday"), NSLocalizedString("TeamEditModalMainScreenViewModelWeekdaySunday", comment: "Sunday")]
    ]
}
